### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by ivan-moto** [pietvandongen/css-for-programmers#1]
I've read the readme, set up the project, and looked at the provided html files but it's not clear what I should be doing. What exactly should I be doing? I'm interested in upping my css game. 

Thank you,
Ivan

**Comment by pietvandongen** [comment]
Hi Ivan,

Thanks for you interest in the project! I'm afraid there's not much more to the project than this. I usually use it to teach people about CSS by doing a lecture then letting them write some CSS using this project.

One of the things we usually do is try to copy a website by writing HTML and CSS incrementally to make it look similar. You could use this project to do so, by running the local server and tweaking the HTML and CSS files.

Cheers,

Piet
